### ISSUE TITLE
遇到空指针异常

### ISSUE THREAD

**Issue by feimenggo** [quickmsg/smqtt#19]
```
12:13:48.153 [business-io-1262] ERROR i.g.q.core.protocol.PublishProtocol - error
java.lang.NullPointerException: null
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1693)
	at io.github.quickmsg.core.spi.DefaultMessageRegistry.saveSessionMessage(DefaultMessageRegistry.java:32)
	at io.github.quickmsg.core.protocol.PublishProtocol.filterOfflineSession(PublishProtocol.java:128)
	at io.github.quickmsg.core.protocol.PublishProtocol.lambda$send$0(PublishProtocol.java:102)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:178)
	at java.base/java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1707)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at io.github.quickmsg.core.protocol.PublishProtocol.send(PublishProtocol.java:109)
	at io.github.quickmsg.core.protocol.PublishProtocol.parseProtocol(PublishProtocol.java:68)
	at io.github.quickmsg.common.protocol.Protocol.lambda$doParseProtocol$0(Protocol.java:27)
	at reactor.core.publisher.MonoDeferContextual.subscribe(MonoDeferContextual.java:47)
	at reactor.core.publisher.Mono.subscribe(Mono.java:4338)
	at reactor.core.publisher.MonoSubscribeOn$SubscribeOnSubscriber.run(MonoSubscribeOn.java:126)
	at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:84)
	at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:37)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by feimenggo** [comment]
<img width="1394" alt="image" src="https://user-images.githubusercontent.com/12608693/185564651-4399aaf9-ebf2-4901-863f-7160d471adbf.png">

**Comment by 1ssqq1lxr** [comment]
这种是，没有发送connect报文，导致，



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年8月19日(周五) 下午3:16
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: Re: [quickmsg/smqtt] 遇到空指针异常 (Issue #19)

**Comment by feimenggo** [comment]
> 这种是，没有发送connect报文，导致，
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2022年8月19日(周五) 下午3:16 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; 主题: Re: [quickmsg/smqtt] 遇到空指针异常 (Issue #19) — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt;

请问应该怎么解决呢？重启smqtt后正常了，有可能后面还会遇到。

**Comment by 1ssqq1lxr** [comment]
能提供更详细得日志吗？可以试用我们商业版



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年8月19日(周五) 下午5:32
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [quickmsg/smqtt] 遇到空指针异常 (Issue #19)




  
这种是，没有发送connect报文，导致，
 …
 ---原始邮件--- 发件人: @.&gt; 发送时间: 2022年8月19日(周五) 下午3:16 收件人: @.&gt;; 抄送: @.&gt;; 主题: Re: [quickmsg/smqtt] 遇到空指针异常 (Issue #19) — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: @.&gt;
  
请问应该怎么解决呢？重启smqtt后正常了，有可能后面还会遇到。

**Comment by feimenggo** [comment]
> 能提供更详细得日志吗？可以试用我们商业版
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2022年8月19日(周五) 下午5:32 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [quickmsg/smqtt] 遇到空指针异常 (Issue #19) 这种是，没有发送connect报文，导致， … ---原始邮件--- 发件人: @.&gt; 发送时间: 2022年8月19日(周五) 下午3:16 收件人: @.&gt;; 抄送: @.&gt;; 主题: Re: [quickmsg/smqtt] 遇到空指针异常 (Issue #19) — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: @.&gt; 请问应该怎么解决呢？重启smqtt后正常了，有可能后面还会遇到。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

没有更详细的日志了，我是发现消息发布后，订阅没有收到消息，查日志才发现这个问题。

**Comment by feimenggo** [comment]
又遇到这个问题了

<img width="1083" alt="image" src="https://user-images.githubusercontent.com/12608693/185722188-f098051d-0aac-4541-b336-9285f6de7fa4.png">

我在filterOfflineSession方法里加了判断ChannelStatus.OFFLINE，才执行saveSessionMessage方法。

**Comment by 1ssqq1lxr** [comment]
加微信17512575402



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年8月19日(周五) 中午12:19
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [quickmsg/smqtt] 遇到空指针异常 (Issue #19)




 12:13:48.153 [business-io-1262] ERROR i.g.q.core.protocol.PublishProtocol - error java.lang.NullPointerException: null at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1693) at io.github.quickmsg.core.spi.DefaultMessageRegistry.saveSessionMessage(DefaultMessageRegistry.java:32) at io.github.quickmsg.core.protocol.PublishProtocol.filterOfflineSession(PublishProtocol.java:128) at io.github.quickmsg.core.protocol.PublishProtocol.lambda$send$0(PublishProtocol.java:102) at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:178) at java.base/java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1707) at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921) at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682) at io.github.quickmsg.core.protocol.PublishProtocol.send(PublishProtocol.java:109) at io.github.quickmsg.core.protocol.PublishProtocol.parseProtocol(PublishProtocol.java:68) at io.github.quickmsg.common.protocol.Protocol.lambda$doParseProtocol$0(Protocol.java:27) at reactor.core.publisher.MonoDeferContextual.subscribe(MonoDeferContextual.java:47) at reactor.core.publisher.Mono.subscribe(Mono.java:4338) at reactor.core.publisher.MonoSubscribeOn$SubscribeOnSubscriber.run(MonoSubscribeOn.java:126) at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:84) at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:37) at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by leafseelight** [comment]
> 又遇到这个问题了
> 
> <img alt="图像" width="1083" src="https://user-images.githubusercontent.com/12608693/185722188-f098051d-0aac-4541-b336-9285f6de7fa4.png">
> 
> 我在filterOfflineSession方法里加了判断ChannelStatus.OFFLINE，才执行saveSessionMessage方法。

您好，filterOfflineSession方法里加判断ChannelStatus.OFFLINE，才执行saveSessionMessage方法，这样好使吗？

**Comment by feimenggo** [comment]
好使

**Comment by leafseelight** [comment]
老铁，你是用什么版本呢？我1.0.7跑3年了，你是什么版本处理这个问题，跑到现在都再没出过问题吗？







&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "quickmsg/smqtt"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年9月14日(星期六) 晚上11:49
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [quickmsg/smqtt] 遇到空指针异常 (Issue #19)





 
好使

**Comment by feimenggo** [comment]
现在没有用这个库了。当时修改后，几个月没有再报错，但不知道有没有其他影响。

**Comment by leafseelight** [comment]
> 现在没有用这个库了。当时修改后，几个月没有再报错，但不知道有没有其他影响。

感谢分享！您现在用哪个库？我也学习一下
